"""
            ADDIS ABABA SCIENCE AND TECHNOLOGY UNIVERSITY
             COLLEGE OF ELECTRICAL AND MECHANICAL ENGINEERING
                DEPARTMENTS OF ELECTRICAL AND COMPUTER ENGINEERING
                  (COMPUTER ENGINEERING STREAM)
                     Advanced programing Assignment
                     ===================================
                          Section : C
                             Name : Yosef Emyayu
                               Id : Ets1310/10
                                submitted to Mr. Eyob B.
"""
from sourceCode import Assignment

assignment = Assignment()
print("========================================================================")
print("Quation 1")
print('      Cub of the given number = ',assignment.cube(3))
print("========================================================================")
print("Quation 2")
print('       Triangle Area = ',assignment.triangle(5,40))
print("========================================================================")
print("Quation 3")
print('       Rectangle Area = ',assignment.rectangle(5,40))
print("========================================================================")
print("Quation 4")
print('       The value of "y" for the line with given  m,x,b is :',assignment.line(2,4,5))
print("========================================================================")
print("Quation 5")

print('       is the given two lines intersect: result= ',assignment.intersect(5,40,4,5))
print("========================================================================")
print("Quation 6")
print('       Factorial of the given number = ',assignment.factorials(5))
print("========================================================================")
print("Quation 7")
assignment.fibonacci()
print("========================================================================")
print("Quation 8A")
print('       is the given number prime :',assignment.PrimeChecking(5))
print("Quation 8B")
print('       Sum of the digit =',assignment.sumOfDigit(1234))
print("========================================================================")
print("Quation 9")
print('       The given numbers sorted in ascending:',assignment.ascendingOrder([1,54,78,95,2,5,2,78,4,2,4,0]))
print("========================================================================")
print("Quation 10")
assignment.markAbove20()
print("========================================================================")
print("Quation 11")
assignment.phoneNumber()
print("========================================================================")
print("Quation 12")
assignment.maxAndMin()
print("========================================================================")
print("Quation 13")
assignment.reverse()
print("========================================================================")
print("Quation 14")
assignment.gcd()
print("========================================================================")
print("Quation 15")
assignment.lcm()
print("========================================================================")
print("Quation 16")
assignment.sumOfSerious()
print("========================================================================")
print("Quation 17")
assignment.isbn()
print("========================================================================")
print("Quation 18")
assignment.exp()
print("========================================================================")
print("Quation 19")
assignment.leapYear()
print("========================================================================")
print("Quation 20")
assignment.largestAndOccurrence()
print("========================================================================")
print("Quation 21")
assignment.numWithDigitCube()
print("========================================================================")
print("Quation 22")
assignment.digitcount()
print("========================================================================")
print("Quation 23")
assignment.primeCount()
print("========================================================================")
print("Quation 24")
assignment.isPerfectNUmber()
print("========================================================================")
print("Quation 25")
assignment.countNumAve()
print("========================================================================")
print("Quation 26")
assignment.tutionCost()
print("========================================================================")
print("Quation 27")
assignment.conversion()
print("========================================================================")
print("Quation 28")
assignment.topTwoStudents()
print("========================================================================")
print("Quation 29")
assignment.topOneStudent()
print("========================================================================")
print("Quation 30")
assignment.multOf5and6NotBoth()
print("========================================================================")
print("Quation 31")
assignment.ascii()
print("========================================================================")
print("Quation 32A")
assignment.patternA()
print("Quation 32A")
assignment.patternB()
print("========================================================================")
print("Quation 33")
assignment.patternPyramid()
print("========================================================================")
print("Quation 34")
assignment.patternPascal()
print("========================================================================")
print("Quation 35")
assignment.loanAmountPeriod()
print("========================================================================")
print("Quation 36")
assignment.toHexadecomal()
print("========================================================================")
print("Quation 37")
assignment.eulers_number()
print("========================================================================")

print("Quation 38")
assignment.isPrime()
print("========================================================================")


print("Quation 39")
assignment.isEven()
print("========================================================================")

print("Quation 40")
assignment.calculator()
print("========================================================================")

print("Quation 41")
assignment.factrialsum()
print("========================================================================")









